// ============================================================
// MYTHWRIGHT — EXPORT UTILITIES
// Handles all export formats. Browser-native formats (JSON,
// Markdown, HTML, PNG) run client-side. Pandoc formats are
// generated by calling the /api/pandoc endpoint (or, in the
// desktop/self-hosted case, via a bundled Pandoc worker).
// ============================================================

import type { Outline, Beat, TipTapJSON } from '../types'

// ── Types ────────────────────────────────────────────────────
export type NativeFmt  = 'json' | 'markdown' | 'html' | 'png'
export type PandocFmt  =
  | 'docx' | 'odt' | 'rtf' | 'epub' | 'pdf'
  | 'rst'  | 'asciidoc' | 'org' | 'mediawiki' | 'textile'
  | 'latex' | 'man' | 'plain' | 'gfm' | 'jira' | 'dokuwiki'
  | 'fb2' | 'typst' | 'opendocument' | 'pptx'

export type ExportFormat = NativeFmt | PandocFmt

export interface ExportFormatMeta {
  id:          ExportFormat
  label:       string
  ext:         string
  mime:        string
  icon:        string
  group:       'native' | 'document' | 'web' | 'markup' | 'slides'
  description: string
  native?:     boolean   // runs in-browser, no server needed
}

export const EXPORT_FORMATS: ExportFormatMeta[] = [
  // ── Native (in-browser) ─────────────────────────────────────
  { id:'json',         label:'JSON',         ext:'json',   mime:'application/json',           icon:'🗃️', group:'native',   description:'Full data backup — re-importable',           native:true },
  { id:'markdown',     label:'Markdown',     ext:'md',     mime:'text/markdown',              icon:'📝', group:'native',   description:'Obsidian, Logseq, GitHub',                   native:true },
  { id:'html',         label:'HTML',         ext:'html',   mime:'text/html',                  icon:'🌐', group:'native',   description:'Styled standalone document',                 native:true },
  { id:'png',          label:'PNG',          ext:'png',    mime:'image/png',                  icon:'🖼️', group:'native',   description:'Visual screenshot of canvas',                native:true },
  // ── Document formats (Pandoc) ───────────────────────────────
  { id:'docx',         label:'Word (.docx)', ext:'docx',   mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document', icon:'📄', group:'document', description:'Microsoft Word' },
  { id:'odt',          label:'OpenDoc',      ext:'odt',    mime:'application/vnd.oasis.opendocument.text',                                  icon:'📄', group:'document', description:'LibreOffice / OpenOffice' },
  { id:'rtf',          label:'RTF',          ext:'rtf',    mime:'application/rtf',            icon:'📄', group:'document', description:'Universal rich text' },
  { id:'epub',         label:'EPUB',         ext:'epub',   mime:'application/epub+zip',       icon:'📚', group:'document', description:'E-book format' },
  { id:'pdf',          label:'PDF',          ext:'pdf',    mime:'application/pdf',            icon:'📕', group:'document', description:'Print / archive' },
  { id:'typst',        label:'Typst',        ext:'typ',    mime:'text/plain',                 icon:'📐', group:'document', description:'Modern typesetting' },
  { id:'pptx',         label:'PowerPoint',   ext:'pptx',   mime:'application/vnd.openxmlformats-officedocument.presentationml.presentation', icon:'📊', group:'slides', description:'One slide per beat' },
  // ── Markup (Pandoc) ─────────────────────────────────────────
  { id:'rst',          label:'reStructured', ext:'rst',    mime:'text/x-rst',                 icon:'🔤', group:'markup',   description:'Sphinx / Python docs' },
  { id:'asciidoc',     label:'AsciiDoc',     ext:'adoc',   mime:'text/asciidoc',              icon:'🔤', group:'markup',   description:'Technical writing' },
  { id:'org',          label:'Org Mode',     ext:'org',    mime:'text/plain',                 icon:'🔤', group:'markup',   description:'Emacs Org Mode' },
  { id:'latex',        label:'LaTeX',        ext:'tex',    mime:'text/x-latex',               icon:'🔤', group:'markup',   description:'Academic typesetting' },
  { id:'gfm',          label:'GitHub MD',    ext:'md',     mime:'text/markdown',              icon:'🐙', group:'markup',   description:'GitHub Flavored Markdown' },
  // ── Wiki / web (Pandoc) ─────────────────────────────────────
  { id:'mediawiki',    label:'MediaWiki',    ext:'wiki',   mime:'text/plain',                 icon:'🌍', group:'web',     description:'Wikipedia-style markup' },
  { id:'jira',         label:'Jira',         ext:'jira',   mime:'text/plain',                 icon:'🔵', group:'web',     description:'Jira wiki markup' },
  { id:'dokuwiki',     label:'DokuWiki',     ext:'txt',    mime:'text/plain',                 icon:'📖', group:'web',     description:'DokuWiki syntax' },
  { id:'textile',      label:'Textile',      ext:'textile',mime:'text/plain',                 icon:'🧵', group:'web',     description:'Redmine / Basecamp' },
  { id:'fb2',          label:'FictionBook',  ext:'fb2',    mime:'application/xml',            icon:'📖', group:'document', description:'Russian e-book standard' },
  { id:'man',          label:'Man Page',     ext:'1',      mime:'text/troff',                 icon:'💻', group:'markup',  description:'Unix man page format' },
  { id:'plain',        label:'Plain Text',   ext:'txt',    mime:'text/plain',                 icon:'📃', group:'markup',  description:'No formatting' },
]

// ── TipTap JSON → Markdown (native) ─────────────────────────
function nodeToMd(node: Record<string, unknown>, depth = 0): string {
  const type    = node.type as string
  const content = (node.content as Record<string, unknown>[] | undefined) ?? []
  const text    = (node.text as string | undefined) ?? ''
  const marks   = (node.marks as {type:string}[] | undefined) ?? []

  if (type === 'text') {
    let out = text
    if (marks.some(m => m.type === 'bold'))   out = `**${out}**`
    if (marks.some(m => m.type === 'italic')) out = `*${out}*`
    if (marks.some(m => m.type === 'code'))   out = `\`${out}\``
    return out
  }
  const inner = () => content.map(c => nodeToMd(c as Record<string,unknown>, depth)).join('')
  switch (type) {
    case 'doc':         return content.map(c => nodeToMd(c as Record<string,unknown>)).join('\n\n')
    case 'paragraph':   return inner()
    case 'heading':     return `${'#'.repeat((node.attrs as {level:number})?.level ?? 2)} ${inner()}`
    case 'bulletList':  return content.map(c => `- ${nodeToMd(c as Record<string,unknown>)}`).join('\n')
    case 'orderedList': return content.map((c, i) => `${i+1}. ${nodeToMd(c as Record<string,unknown>)}`).join('\n')
    case 'listItem':    return inner().trim()
    case 'blockquote':  return inner().split('\n').map(l => `> ${l}`).join('\n')
    case 'hardBreak':   return '\n'
    default:            return inner()
  }
}

function tipTapToMarkdown(json: TipTapJSON | null | undefined): string {
  if (!json) return ''
  try { return nodeToMd(json as Record<string, unknown>) }
  catch { return '' }
}

// ── Outline → Markdown document ─────────────────────────────
function outlineToMarkdown(outline: Outline, beats: Beat[]): string {
  const sorted = [...beats].sort((a, b) => a.position - b.position)
  const lines: string[] = [`# ${outline.title}\n`]

  // Narrative anchors
  const dq = tipTapToMarkdown(outline.dramaticQuestion as TipTapJSON)
  const ll = tipTapToMarkdown(outline.logline          as TipTapJSON)
  const th = tipTapToMarkdown(outline.themeStated      as TipTapJSON)
  if (dq) lines.push(`> **Dramatic Question:** ${dq}\n`)
  if (ll) lines.push(`> **Logline:** ${ll}\n`)
  if (th) lines.push(`> **Theme:** ${th}\n`)
  if (dq || ll || th) lines.push('')

  sorted.forEach((beat, i) => {
    lines.push(`## ${i+1}. ${beat.title}`)
    if (beat.synopsis) lines.push(`\n*${beat.synopsis}*\n`)
    const body = tipTapToMarkdown(beat.bodyJson)
    if (body) lines.push(`\n${body}\n`)
    lines.push('')
  })
  return lines.join('\n')
}

// ── Outline → HTML document ─────────────────────────────────
function outlineToHTML(outline: Outline, beats: Beat[]): string {
  const md = outlineToMarkdown(outline, beats)
  // Simple HTML wrapper with dark-theme inline styles
  const escaped = md
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${outline.title}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px;
         color: #e2e8f0; background: #1a3a3a; line-height: 1.7; }
  h1 { color: #e8933a; font-size: 2em; margin-bottom: 0.3em; }
  h2 { color: #5ec8c8; font-size: 1.3em; margin-top: 2em; border-bottom: 1px solid #2a5050; padding-bottom: 0.3em; }
  blockquote { border-left: 3px solid #5ec8c8; margin: 0; padding: 0.5em 1em; color: #a8c8c8; }
  em  { color: #a8c8c8; }
  code{ background: #0d2626; padding: 2px 5px; border-radius: 3px; font-size: 0.9em; }
  pre { background: #0d2626; padding: 1em; border-radius: 6px; overflow: auto; }
</style>
</head>
<body>
<pre>${escaped}</pre>
</body>
</html>`
}

// ── Trigger download ─────────────────────────────────────────
function download(content: string | Blob, filename: string, mime: string) {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mime })
  const url  = URL.createObjectURL(blob)
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename })
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Revoke after tick to ensure download initiated
  setTimeout(() => URL.revokeObjectURL(url), 100)
}

// ── PNG export via html-to-image ─────────────────────────────
async function exportPNG(outlineId: string, title: string): Promise<void> {
  const { toPng } = await import('html-to-image')
  const canvas = document.querySelector(`[data-outline-id="${outlineId}"] .react-flow__viewport`)
              ?? document.querySelector('main')
  if (!canvas) throw new Error('Canvas element not found')
  const dataUrl = await toPng(canvas as HTMLElement, { quality: 0.95, pixelRatio: 2 })
  // Convert data URL to blob without fetch (works in all environments)
  const byteStr = atob(dataUrl.split(',')[1])
  const bytes   = new Uint8Array(byteStr.length)
  for (let i = 0; i < byteStr.length; i++) bytes[i] = byteStr.charCodeAt(i)
  download(new Blob([bytes], { type: 'image/png' }), `${title}.png`, 'image/png')
}

// ── Pandoc export via server endpoint ────────────────────────
// In the self-hosted flow, users run a tiny local Pandoc bridge.
// In the cloud flow, this calls a Supabase Edge Function.
async function exportViaPandoc(
  markdown: string,
  fmt: PandocFmt,
  title: string
): Promise<void> {
  const meta = EXPORT_FORMATS.find(f => f.id === fmt)
  if (!meta) throw new Error(`Unknown format: ${fmt}`)

  // Try local Pandoc bridge (self-hosted mode on localhost)
  const localUrl = 'http://localhost:4567/convert'
  try {
    const resp = await fetch(localUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ markdown, format: fmt, title }),
      signal: AbortSignal.timeout(15_000),
    })
    if (resp.ok) {
      const blob = await resp.blob()
      download(blob, `${title}.${meta.ext}`, meta.mime)
      return
    }
  } catch {
    // Local bridge not running — fall through to clipboard/copy approach
  }

  // Fallback: copy Markdown to clipboard + instruct user
  await navigator.clipboard.writeText(markdown)
  throw new Error(
    `Pandoc bridge not running. Markdown copied to clipboard.\n` +
    `Run: echo "<clipboard>" | pandoc -f markdown -t ${fmt} -o "${title}.${meta.ext}"`
  )
}

// ── Main export entry point ──────────────────────────────────
export async function exportOutline(
  outline: Outline,
  beats:   Beat[],
  fmt:     ExportFormat
): Promise<{ ok: boolean; message?: string }> {
  const title = outline.title.replace(/[^a-zA-Z0-9 _-]/g, '').trim() || 'outline'

  try {
    switch (fmt) {
      case 'json': {
        const data = JSON.stringify({ outline, beats }, null, 2)
        download(data, `${title}.json`, 'application/json')
        break
      }
      case 'markdown': {
        const md = outlineToMarkdown(outline, beats)
        download(md, `${title}.md`, 'text/markdown')
        break
      }
      case 'html': {
        const html = outlineToHTML(outline, beats)
        download(html, `${title}.html`, 'text/html')
        break
      }
      case 'png': {
        await exportPNG(outline.id, title)
        break
      }
      default: {
        const md = outlineToMarkdown(outline, beats)
        await exportViaPandoc(md, fmt as PandocFmt, title)
        break
      }
    }
    return { ok: true }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { ok: false, message }
  }
}
